<?php

use Illuminate\Database\Seeder;
use App\Models\School;

class SchoolTableSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $schools = [            
         'Trường THPT Ba Vì',
         'Trường THPT Bắc Lương Sơn',
         'Trường THPT Bắc Thăng Long',
         'Trường THPT Bất Bạt',
         'Trường THPT Cao Bá Quát-Gia Lâm',
         'Trường THPT Cao Bá Quát-Quốc Oai',
         'Trường THPT Cầu Giấy',
         'Trường THPT Chu Văn An',
         'Trường THPT Chuyên Đại học Sư phạm',
         '>Trường THPT Chuyên Hà Nội-Amsterdam',
         'Trường THPT Chuyên KHTN',
         'Trường THPT Chuyên Nguyễn Huệ',
         'Trường THPT Chuyên Ngữ ĐH Ngoại ngữ',
         'Trường THPT Chúc Động',
         'Trường THPT Chương Mỹ A',
         'Trường THPT Chương Mỹ B',
         'Trường THPT Cổ Loa',
         'PT Dân tộc nội trú',
         'Trường THPT Dương Xá',
         'Trường THPT Đa Phúc',
         'Trường THPT Đại Cường',
         'ĐH Lâm Nghiệp',
         'Trường THPT Đại Mỗ',
         'Trường THPT Đan Phượng',
         'Trường THPT Đoàn Kết-Hai Bà Trưng',
         'Trường THPT Đông Anh',
         'Trường THPT Đồng Quan',
         'Trường THPT Đống Đa',
         'Trường THPT Hai Bà Trưng-Thạch Thất',
         'Trường THPT Hoài Đức A',
         'Trường THPT Hoài Đức B',
         'Trường THPT Hoàng Cầu',
         'Trường THPT Hoàng Văn Thụ',
         'Trường THPT Hồng Thái',
         'Trường THPT Hợp Thanh',
         'Hữu Nghị T78',
         'Hữu Nghị 80',
         'Trường THPT Kim Anh',
         'Trường THPT Kim Liên',
         'Trường THPT Lê Quý Đôn-Đống Đa',
         'Trường THPT Lê Quý Đôn-Hà Đông',
         'Trường THPT Liên Hà',
         'Trường THPT Lưu Hoàng',
         'Trường THPT Lý Thường Kiệt',
         'Trường THPT Lý Tử Tấn',
         'Trường THPT Mê Linh',
         'Trường THPT Minh Khai',
         'Trường THPT Minh Phú',
         'Trường THPT Mỹ Đức A',
         'Trường THPT Mỹ Đức B',
         'Trường THPT Mỹ Đức C',
         'Trường THPT Ngọc Hồi',
         'Trường THPT Ngọc Tảo',
         'Trường THPT Ngô Quyền-Ba Vì',
         'Trường THPT Ngô Thì Nhậm',
         'Trường THPT Nguyễn Du-Thanh Oai',
         'Trường THPT Nguyễn Gia Thiều',
         'THCS&amp;Trường THPT Nguyễn Tất Thành',
         'Trường THPT Nguyễn Thị Minh Khai',
         'Trường THPT Nguyễn Trãi-Ba Đình',
         'Trường THPT Nguyễn Trãi-Thường Tín',
         'Trường THPT Nguyễn Văn Cừ',
         'Trường THPT Nhân Chính',
         'Trường THPT  Phan Đình Phùng',
         'Trường THPT Phan Huy Chú-Đống Đa',
         'Trường THPT Phạm Hồng Thái',
         'PT năng khiếu TDTT Hà Nội',
         'Trường THPT Phùng Khắc Khoan-Thạch Thất',
         'Trường THPT Phú Xuyên A',
         'Trường THPT Phú Xuyên B',
         'Trường THPT Phúc Thọ',
         'Trường THPT Quang Minh',
         'Trường THPT Quang Trung-Đống Đa',
         'Trường THPT Quang Trung-Hà Đông',
         'Trường THPT Quảng Oai',
         'Trường THPT Quốc Oai',
         'Trường THPT Sóc Sơn',
         'Trường THPT Sơn Tây',
         'Trường THPT Tân Dân',
         'Trường THPT Tân Lập',
         'Trường THPT Tây Hồ',
         'Trường THPT Thanh Oai A',
         'Trường THPT Thanh Oai B',
         'Trường THPT Thạch Bàn',
         'Trường THPT Thạch Thất',
         'Trường THPT Thăng Long',
         'Trường THPT Thực nghiệm',
         'Trường THPT Thường Tín',
         'Trường THPT Thượng Cát',
         'Trường THPT Tiền Phong',
         'Trường THPT Tiến Thịnh',
         'Trường THPT Tô Hiệu-Thường Tín',
         'Trường THPT Trần Đăng Ninh',
         'Trường THPT Trần Hưng Đạo-Hà Đông',
         'Trường THPT Trần Hưng Đạo-Thanh Xuân',
         'Trường THPT Trần Nhân Tông',
         'Trường THPT Trần Phú-Hoàn Kiếm',
         'THCS-Trường THPT Trần Quốc Tuấn',
         'Trường THPT Trung Giã',
         'Trường THPT Trung Văn',
         'Trường THPT Trương Định',
         'Trường THPT Tùng Thiện',
         'Trường THPT  Tự Lập',
         'Trường THPT Ứng Hoà A',
         'Trường THPT Ứng Hoà B',
         'Trường THPT Vạn Xuân-Hoài Đức',
         'Trường THPT Vân Cốc',
         'Trường THPT Vân Nội',
         'Trường THPT Vân Tảo',
         'Trường THPT Việt-Đức',
         'Trường THPT Việt Nam-Ba Lan',
         'Trường THPT  Xuân Đỉnh',
         'Trường THPT Xuân Giang',
         'Trường THPT Xuân Khanh',
         'Trường THPT Xuân Mai',
         'Trường THPT Yên Hoà',
         'Trường THPT Yên Lãng',
         'Trường THPT Yên Viên',
         'THCS&amp;Trường THPT Alfred Nobel',
         'Trường THPT An Dương Vương',
         'Trường THPT Bắc Hà-Đống Đa',
         'Trường THPT Bắc Hà-Thanh Oai',
         'Trường THPT Bắc Đuống',
         'Trường THPT Bình Minh',
         'Trường THPT Đào Duy Từ',
         'Trường THPT Đại Việt',
         'Trường THPT DL Đặng Thai Mai',
         'Trường THPT Đặng Tiến Đông',
         'Trường THPT Đinh Tiên Hoàng-Ba Đình',
         'Trường THPT DL Đoàn Thị Điểm',
         'Trường THPT Đông Đô',
         'Trường THPT Đông Kinh',
         'Trường THPT Einstein',
         'Trường THPT Hà Nội  Academy',
         'Trường THPT Hà Đông',
         'Trường THPT DL Hà Nội',
         'THCS-Trường THPT Hà Thành',
         'Trường THPT Hermann Gmeiner',
         'Trường THPT Hoàng Diệu',
         'Trường THPT Hoàng Long',
         'Trường THPT Hồ Tùng Mậu',
         'Trường THPT Hồ Xuân Hương',
         'Trường THPT Hồng Bàng',
         'PT Hồng Đức',
         'Trường THPT Hồng Hà',
         'Trường THPT Huỳnh Thúc Kháng',
         'Trường THPT Lam Hồng',
         'Trường THPT Lạc Long Quân',
         'Trường THPT Lê Hồng Phong',
         'Trường THPT Lê Ngọc Hân',
         'Trường THPT Lê Thánh Tông',
         'Trường THPT Lê Văn Thiêm',
         'Trường THPT M.V.Lômônôxốp',
         'Trường THPT Lương Thế Vinh-Ba Vì',
         'Trường THPT Lương Thế Vinh',
         'Trường THPT Lương Văn Can',
         'Trường THPT Lý Thái Tổ',
         'Trường THPT Lý Thánh Tông',
         'Trường THPT Mai Hắc Đế',
         'Trường THPT Mari Cuire',
         'Trường THPT Mạc Đĩnh Chi',
         'Trường THPT Minh Trí',
         'THCS-Trường THPT Newton',
         'Trường THPT Ngô Quyền-Đông Anh',
         'Trường THPT Ngô Sỹ Liên',
         'Trường THPT Ngô Tất Tố',
         'Trường THPT Nguyễn Bỉnh Khiêm-Cầu Giấy',
         'Trường THPT Nguyễn Bỉnh Khiêm',
         'Trường THPT Nguyễn Du-Mê Linh',
         'Trường THPT Nguyễn Đình Chiểu',
         'Trường THPT Nguyễn Siêu',
         'Trường THPT Nguyễn Tất Thành-Sơn Tây',
         'Trường THPT DL Nguyễn Thượng Hiền',
         'Trường THPT Nguyễn Thượng Hiền',
         'Trường THPT Nguyễn Trường Tộ',
         'PT Nguyễn Trực',
         'Trường THPT Nguyễn Văn Huyên',
         'Trường THPT Olympia',
         'Trường THPT Phan Bội Châu',
         'Trường THPT Phan Chu Trinh',
         'Trường THPT Phan Huy Chú-Thạch Thất',
         'Trường THPT Phạm Ngũ Lão',
         'Trường THPT  Phùng Hưng',
         'Trường THPT DL Phùng Khắc Khoan',
         'PT Phú Bình',
         'Trường THPT Phương Nam',
         'THCS-Trường THPT Quốc tế Thăng Long',
         'PT Quốc Tế Việt Nam',
         'Song ngữ QT Horizon',
         'Trường THPT Tây Đô',
         'Trường THPT Tây Sơn',
         'Trường THPT Tô Hiến Thành',
         'Trường THPT Tô Hiệu-Gia Lâm',
         'Trường THPT Trần Đại Nghĩa',
         'Trường THPT Trần Phú-Ba Vì',
         'Trường THPT DL Trần Quang Khải',
         'Trường THPT Trí Đức',
         'Trường THPT Vạn Xuân-Long Biên',
         'Trường THPT Văn Hiến',
         'Trường THPT Văn Lang',
         'Trường THPT TT Việt Úc Hà Nội',
         'Trường THPT Wellspring-Mùa Xuân',
         'Trường THPT Xa La',
         'Trường THPT Xuân Thuỷ',
         'Trường THPT Đinh Tiên Hoàng - Mỹ Đức',
         'Trường THPT Đông Nam Á',
         'Trường THPT FPT',
         'Trường THPT Lê Lợi ',
         'Trường THPT TT  Minh Khai',
         'Trường THPT Ngô Gia Tự',
         'Trường THPT Phạm Văn Đồng',
         'Trường THPT Thanh Xuân',
         'Trường THPT Trần Thánh Tông',
         'PT Võ Thuật Bảo Long',
         'GDTX Ba Đình',
         'GDTX Ba Vì',
         'GDTX&amp;DN Cầu Giấy',
         'GDTX Chương Mỹ',
         'GDTX Đan Phượng',
         'GDTX Đình Xuyên',
         'GDTX Đông Anh',
         'GDTX Đông Mỹ',
         'GDTX Đống Đa',
         'GDTX Hai Bà Trưng',
         'GDTX Hà Tây',
         'GDTX Hoài Đức',
         'GDTX Hoàng Mai',
         'GDTX Mê Linh',
         'GDTX Mỹ Đức',
         'GDTX Nguyễn Văn Tố',
         'GDTX Phú Thị',
         'GDTX Phú Xuyên',
         'GDTX Phúc Thọ',
         'GDTX Quốc Oai',
         'GDTX Sóc Sơn',
         'GDTX Sơn Tây',
         'GDTX Tây Hồ',
         'GDTX Thanh Oai',
         'GDTX Thanh  Trì',
         'GDTX Thanh Xuân',
         'GDTX Thạch Thất',
         'GDTX Thường Tín',
         'GDTX Từ Liêm',
         'GDTX Ứng Hoà',
         'GDTX Việt Hưng',
         'Cao đẳng Nghệ thuật Hà Nội',
         'BTVH Công ty Xây dựng',
         'Học viện âm nhạc QGVN',
         'Trung cấp Quang Trung',
         'Trung cấp NT Xiếc và TK Việt Nam',
         'CĐ Kỹ thuật thiết bị y tế',
         'CĐ nghề bách Khoa',
         'CĐ nghề Bách Khoa Hà Nội',
         'CĐ nghề cơ điện Hà Nội',
         'CĐ nghề công nghệ cao Hà Nội',
         'CĐ nghề Công nghiệp Hà Nội',
         'CĐ nghề điện',
         'CĐ nghề đường sắt I',
         'CĐ nghề Giao thông vận tải Trung ương I',
         'CĐ nghề Hùng Vương',
         'CĐ nghề kinh doanh và công nghệ Hà Nội',
         'CĐ nghề KT công nghệ LOD - Phân hiệu HN',
         'CĐ nghề kỹ thuật - công nghệ - kinh tế S',
         'CĐ nghề Kỹ thuật Công nghệ',
         'CĐ nghề Kỹ thuật Mỹ nghệ Việt Nam',
         'CĐ nghề Long Biên',
         'CĐ nghề Phú Châu',
         'CĐ nghề Thăng Long',
         'CĐ nghề Trần Hưng Đạo',
         'CĐ nghề Văn Lang Hà Nội',
         'CĐ nghề VIGLACERA',
         'TC nghề Cơ điện và Chế biến thực phẩm Hà',
         'TC nghề Cơ khí 1 Hà Nội',
         'TC nghề Cơ khí xây dựng',
         'TC nghề Công đoàn Việt Nam',
         'TC nghề Công nghệ ôtô',
         'TC nghề Công nghệ Tây An',
         'TC nghề Công trình I',
         'TC nghề Dân lập CN và NV tổng hợp HN',
         'TC nghề Dân lập Cờ Đỏ',
         'TC nghề Dân lập Công nghệ Thăng Long',
         'TC nghề Dân lập Kỹ nghệ thực hành Tây Mỗ',
         'TC nghề Dân lập Kỹ thuật tổng hợp Hà Nội',
         'TC nghề Dân lập Quang Trung',
         'TC nghề Đào tạo nhân lực Vinaconex',
         'TC nghề đồng hồ - điện tử - tin học HN',
         'TC nghề Du lịch Hà Nội',
         'TC nghề Giao thông Công chính Hà Nội',
         'TC nghề Giao thông Vận tải',
         'TC nghề Giao thông Vận tải Thăng Long',
         'TC nghề Kinh tế Kỹ thuật vinamotor',
         'TC nghề Kỹ nghệ thực hành HIPT',
         'TC nghề kỹ thuật công nghệ vạn xuân',
         'TC nghề Kỹ thuật và Công nghệ',
         'TC nghề Kỹ thuật và Nghiệp vụ Du lịch Qu',
         'TC nghề Kỹ thuật và Nghiệp vụ XD HN',
         'TC nghề may và thời trang Hà Nội',
         'TC nghề Nấu ăn và Nghiệp vụ khách sạn HN',
         'TC nghề Nhân lực Quốc tế',
         'TC nghề Phùng Khắc Khoan',
         'TC nghề Q. tế Đông dương - Phân hiệu HN',
         'TC nghề số 10',
         'TC nghề số 17',
         'TC nghề số 18',
         'TC nghề số I Hà Nội',
         'TC nghề Sơn Tây',
         'TC nghề T thục Formach',
         'TC nghề Thăng Long',
         'TC nghề thông tin và truyền thông HN',
         'TC nghề Tổng hợp Hà Nội',
         'TC nghề Tư thục ASEAN',
         'TC nghề tư thục Âu Việt',
         'TC nghề Tư thục Điện tử - Cơ khí và Xây',
         'TC nghề Vân Canh',
         'TC nghề Việt Tiệp',
         'TC nghề Việt Úc',
         'Trường Đại học VHNT Quân đội',
         'Trường Nghệ thuật Quân đội',
     ];
     $insert = [];
     foreach($schools as $school)
     {
        array_push($insert, array(
            'name'=>$school,
            'city'=>1,
            'create_at'=>time()
        ));
     }
     DB::table('school')->insert($insert);
     $this->command->info("inserted!");
 }
}
