/*
Navicat MySQL Data Transfer

Source Server         : lop_cua_toi
Source Server Version : 50642
Source Host           : 159.65.34.155:3306
Source Database       : site

Target Server Type    : MYSQL
Target Server Version : 50642
File Encoding         : 65001

Date: 2018-12-20 12:38:56
*/

SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for question_flash_muti
-- ----------------------------
DROP TABLE IF EXISTS `question_flash_muti`;
CREATE TABLE `question_flash_muti` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` int(11) DEFAULT NULL,
  `course_id` int(11) DEFAULT NULL,
  `lesson_id` int(11) DEFAULT NULL,
  `question_id` int(11) DEFAULT NULL,
  `parent_id` int(11) DEFAULT NULL,
  `status` int(11) DEFAULT NULL,
  `question` text COLLATE utf8mb4_unicode_ci,
  `explain_before` text COLLATE utf8mb4_unicode_ci,
  `explain_after` text COLLATE utf8mb4_unicode_ci,
  `img_before` text COLLATE utf8mb4_unicode_ci,
  `img_after` text COLLATE utf8mb4_unicode_ci,
  `create_at` int(11) DEFAULT NULL,
  `question_after` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=123 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ----------------------------
-- Records of question_flash_muti
-- ----------------------------
INSERT INTO `question_flash_muti` VALUES ('1', null, null, '17', '6', '6', null, 'Đây có phải là giáo viên không ?', 'gợi ý cho giáo viên 1', 'gợi ý cho giáo viên 2', '/images/exercise/anh151544415902.jpg', '/images/exercise/anh231544415906.jpg', null, null);
INSERT INTO `question_flash_muti` VALUES ('2', '5', null, '17', '6', '1', null, 'Giáo viên sub 1', 'gợi ý giáo viên sub 1', 'gợi ý giáo viên sub 2', '/images/exercise/anh221544415926.jpg', '/images/exercise/anh301544415930.jpg', null, null);
INSERT INTO `question_flash_muti` VALUES ('3', null, null, '17', '6', '6', null, 'đây có phải là thầy giáo không?', 'gợi ý thầy giáo 1', 'gợi ý thầy giáo 2', '/images/exercise/anh371544415960.jpg', '/images/exercise/anh191544415964.jpg', null, null);
INSERT INTO `question_flash_muti` VALUES ('4', '5', null, '17', '6', '3', null, 'thầy giáo sub đúng ko?', 'gợi ý sub 2', 'gới ý sub 2 2', '/images/exercise/anh171544415987.jpg', '/images/exercise/anh341544415992.jpg', null, null);
INSERT INTO `question_flash_muti` VALUES ('5', null, null, '21', '15', '15', null, 'Câu hỏi cho flashcard chuỗi', 'gợi ý ảnh 1', 'gợi ý ảnh 2', '/images/exercise/course1544621824.jpg', '/images/exercise/Rectangleflash_demo1544621828.png', null, null);
INSERT INTO `question_flash_muti` VALUES ('6', '1', null, '21', '15', '5', null, 'câu hỏi cho card con', 'gợi ý mặt 1', 'gợi ý mặt sau', '/images/exercise/upload_0c844e6fb48a476a931189cd8f690e2e_large1544621851.jpg', '/images/exercise/15433081261544621855.jpg', null, null);
INSERT INTO `question_flash_muti` VALUES ('7', null, null, '21', '15', '15', null, 'cau ahoir', 'gợi ý 1', 'gợi ý 2', '/images/exercise/Beetle-Bug-Origami-Design-215433843801544621870.jpg', '/images/exercise/15431617101544621878.jpg', null, null);
INSERT INTO `question_flash_muti` VALUES ('8', null, null, '33', '44', '44', null, 'Ý thứ nhất', 'hệ thống các quan điểm, học thuyết khoa học, Mác xây dựng, Leenin phát triển', null, null, null, null, 'Là hệ thống các quan điểm và học thuyết khoa học do C.Mác và Ph.Ăngghen xây dựng, V.I.Leenin bảo vệ và phát triển, được hình thành và phát triển dựa trên cơ sở tổng kết thực tiễn và kế thừa những giá trị tư tưởng của nhân loại');
INSERT INTO `question_flash_muti` VALUES ('9', '6', null, '33', '44', '8', null, null, null, null, null, null, null, null);
INSERT INTO `question_flash_muti` VALUES ('10', null, null, '33', '44', '44', null, 'Ý thứ hai', 'thế giới quan, phương pháp luận, chung nhất, nhận thức khoa học, thực tiễn cách mạng', null, null, null, null, 'là thế giới quan, phương pháp luận chung nhất của nhận thức khoa học và thực tiễn cách mạng');
INSERT INTO `question_flash_muti` VALUES ('11', null, null, '33', '44', '44', null, 'ý thứ ba', 'khoa học, sự nghiệp giải phóng các giai cấp vô sản, nhân dân lao động, con người', null, null, null, null, 'là khoa học về sự nghiệp giải phóng giai cấp vô sản, giải phóng nhân dân lao động khỏi mọi chế độ áp bức, bóc lột, và tiến tới giải phóng con người.');
INSERT INTO `question_flash_muti` VALUES ('12', null, null, '36', '46', '46', null, 'Nên Làm như thế nào', null, null, null, null, null, 'Nên làm như thế này');
INSERT INTO `question_flash_muti` VALUES ('13', null, null, '23', '49', '49', null, 'Có bao nhiêu', null, null, null, null, null, 'Không có bao nhiêu');
INSERT INTO `question_flash_muti` VALUES ('23', null, null, '41', '56', '56', null, 'Ý thứ nhất', 'hệ thống các quan điểm, học thuyết khoa học, Mác xây dựng, Lenin phát triển', 'Là hệ thống các quan điểm', '/images/exercise/banner1544973216.jpg', '/images/exercise/logo1544973226.png', null, 'Là hệ thống các quan điểm');
INSERT INTO `question_flash_muti` VALUES ('24', '6', null, '41', '56', '23', null, null, null, null, '/images/exercise/logo1544973433.png', '/images/exercise/1431020461ez_publish_cms_hosting1544973439.png', null, null);
INSERT INTO `question_flash_muti` VALUES ('25', null, null, '41', '56', '56', null, 'Ý thứ hai', 'thế giới quan, phương pháp luận, chung nhất, nhận thức khoa học, thực tiễn cách mạng', 'Là hệ thống các quan điểm', null, null, null, 'là thế giới quan, phương pháp luận chung nhất của nhận thức khoa học và thực tiễn cách mạng');
INSERT INTO `question_flash_muti` VALUES ('26', null, null, '41', '56', '56', null, 'Ý thứ ba', 'khoa học, sự nghiệp giải phóng các giai cấp vô sản, nhân dân lao động, con người', null, null, null, null, 'là khoa học về sự nghiệp giải phóng giai cấp vô sản, giải phóng nhân dân lao động khỏi mọi chế độ áp bức, bóc lột, và tiến tới giải phóng con người.');
INSERT INTO `question_flash_muti` VALUES ('29', null, null, '41', '58', '58', null, 'Ý lớn thứ nhất', null, null, null, null, null, 'Điều kiện kinh tế - xã hội?');
INSERT INTO `question_flash_muti` VALUES ('30', '6', null, '41', '58', '29', null, 'Ý thứ nhất', 'năm 40- thế kỉ 19', null, null, null, null, 'Chủ nghĩa Mác-Lênin ra đời vào những năm 40 của thế kỉ XIX:');
INSERT INTO `question_flash_muti` VALUES ('31', '6', null, '41', '58', '29', null, 'Ý thứ hai', 'phương thức sản xuất tư bản, Tây Âu, phát triển, nền tảng, Cách mạng công nghiệp Anh, thế kỷ 18', null, null, null, null, 'Là thời kỳ phương thức sản xuất tư bản chủ nghĩa ở các nước Tây Âu đã phát triển mạnh mẽ trên nền tảng cuộc cách mạng công nghiệp được diễn ra trước tiên ở Anh vào cuối thế kỉ XVIII.');
INSERT INTO `question_flash_muti` VALUES ('32', '6', null, '41', '58', '29', null, 'Ý thứ ba', 'thủ công tư bản, tư bản chủ nghĩa, giai cấp vô sản', null, null, null, null, 'Cuộc cách mạng công nghiệp đánh dấu bước chuyển biến từ nền sản xuất thủ công tư bản sang nền đại công nghiệp tư bản chủ nghĩa, làm thay đổi sâu sắc cục diện xã hội, trước hết là sự hình thành và phát triển của giai cấp vô sản.');
INSERT INTO `question_flash_muti` VALUES ('36', null, null, '43', '60', '60', null, 'Ý thứ nhất', 'hệ thống các quan điểm, học thuyết khoa học, Mác xây dựng, Lenin phát triển', null, null, null, null, 'Là hệ thống các quan điểm và học thuyết khoa học do C.Mác và Ph.Ăngghen xây dựng, V.I.Leenin bảo vệ và phát triển, được hình thành và phát triển dựa trên cơ sở tổng kết thực tiễn và kế thừa những giá trị tư tưởng của nhân loại');
INSERT INTO `question_flash_muti` VALUES ('37', null, null, '43', '60', '60', null, 'Ý thứ hai', 'thế giới quan, phương pháp luận, chung nhất, nhận thức khoa học, thực tiễn cách mạng', null, null, null, null, 'là thế giới quan, phương pháp luận chung nhất của nhận thức khoa học và thực tiễn cách mạng');
INSERT INTO `question_flash_muti` VALUES ('38', null, null, '43', '60', '60', null, 'Ý thứ ba', 'khoa học, sự nghiệp giải phóng các giai cấp vô sản, nhân dân lao động, con người', null, null, null, null, 'là khoa học về sự nghiệp giải phóng giai cấp vô sản, giải phóng nhân dân lao động khỏi mọi chế độ áp bức, bóc lột, và tiến tới giải phóng con người.');
INSERT INTO `question_flash_muti` VALUES ('39', null, null, '43', '61', '61', null, 'Ý lớn thứ nhất?', null, null, null, null, null, 'Điều kiện kinh tế - xã hội');
INSERT INTO `question_flash_muti` VALUES ('40', '6', null, '43', '61', '39', null, 'Ý thứ nhất', 'Thời gian ra đời', null, null, null, null, 'Chủ nghĩa Mác-Lênin ra đời vào những năm 40 của thế kỉ XIX:');
INSERT INTO `question_flash_muti` VALUES ('41', '6', null, '43', '61', '39', null, 'Ý thứ hai?', 'phương thức sản xuất tư bản, Tây Âu, phát triển, nền tảng, Cách mạng công nghiệp Anh, thế kỷ 18', null, null, null, null, 'Là thời kỳ phương thức sản xuất tư bản chủ nghĩa ở các nước Tây Âu đã phát triển mạnh mẽ trên nền tảng cuộc cách mạng công nghiệp được diễn ra trước tiên ở Anh vào cuối thế kỉ XVIII.');
INSERT INTO `question_flash_muti` VALUES ('42', '6', null, '43', '61', '39', null, 'Ý thứ ba', 'thủ công tư bản, tư bản chủ nghĩa, giai cấp vô sản', null, null, null, null, 'Cuộc cách mạng công nghiệp đánh dấu bước chuyển biến từ nền sản xuất thủ công tư bản sang nền đại công nghiệp tư bản chủ nghĩa, làm thay đổi sâu sắc cục diện xã hội, trước hết là sự hình thành và phát triển của giai cấp vô sản.');
INSERT INTO `question_flash_muti` VALUES ('43', '6', null, '43', '61', '39', null, 'Ý thứ tư', 'mâu thuẫn, lực lượng sản xuất, quan hệ sản xuất, 1825, Pháp, Anh, Đức', null, null, null, null, 'Thời kì này mâu thuẫn sâu sắc giữa Lực lượng sản xuất với Quan hệ sản xuất bộc lộ qua cuộc khủng hoảng kinh tế 1825 và hàng loạt các cuộc đấu tranh của giai cấp công nhân đã nổ ra ở Anh, Pháp, Đức.');
INSERT INTO `question_flash_muti` VALUES ('44', '6', null, '43', '61', '39', null, 'ý thứ năm', 'giai cấp vô sản, độc lập, tiên phong', null, null, null, null, 'Giai cấp vô sản đã trở thành lực lượng chính trị độc lập, tiên phong trong cuộc đấu tranh cho nền dân chủ, công bằng, tiến bộ xã hội. Thực tiễn cách mạng đã đặt ra yêu cầu khách quan là phải có lí luận soi đường và CNMÁC ra đời đã đáp ứng được yêu cầu khách quan đó .');
INSERT INTO `question_flash_muti` VALUES ('45', null, null, '43', '61', '61', null, 'Ý lớn thứ 3 là gì?', null, null, null, null, null, 'Tiền đề lý luận?');
INSERT INTO `question_flash_muti` VALUES ('46', '6', null, '43', '61', '45', null, 'Ý thứ nhất', 'nhu cầu khách quan, kế thừa tinh hoa', null, null, null, null, 'Chủ nghĩa Mác ra đời không chỉ xuất phát từ nhu cầu khách quan lịch sử, mà còn là kết quả của sự kế thừa tinh hoa di sản lý luận của nhân loại, trong đó, trực tiếp nhất là triết học cổ điển Đức, kinh tế học chính trị cổ điển Anh và chủ nghĩa xã hội không tưởng Pháp và Anh:');
INSERT INTO `question_flash_muti` VALUES ('47', '6', null, '43', '61', '45', null, 'ý thứ hai', 'triết học cổ điển Đức, kế thừa, biện chứng - Ph.Hêghen, chủ nghĩa duy vật-L.Phoiơbắc', null, null, null, null, 'Với triết học cổ điển Đức, đặc biệt là triết học của Ph.Hêghen và L.Phoiơbắc đã ảnh hưởng sâu sắc đến sự hình thành thế giới quan và phương pháp luận triết học của chủ nghĩa Mác. Các nhà sáng lập của chủ nghĩa Mác đã kế thừa những nội dung cơ bản trong phép biện chứng của Ph.Hêghen, chủ nghĩa duy vật của L.Phoiơbắc. Khắc phục những những hạn chế cơ bản của hai học thuyết ấy, đó là triết học duy tâm (Hêghen) và phương pháp siêu hình (Phoiơbắc). Sáng lập ra chủ nghĩa duy vật biện chứng và phép biện chứng duy vật và được vận dụng vào nghiên cứu một cách khoa học những quy luật chung nhất của sự phát triển xã hội, nghiên cứu quy luật ra đời, phát triển suy tàn của chủ nghĩa tư bản và sự ra đời tất yếu của Chủ nghĩa xã hội.');
INSERT INTO `question_flash_muti` VALUES ('48', '6', null, '43', '61', '45', null, 'ý thứ 3', 'triết học cổ điển Anh, kế thừa, quan điểm hợp lý khoa học, A.Xmít, Đ.Ricácđô, giá trị thặng dư,', null, null, null, null, 'Với kinh tế học chính trị cổ điển Anh, đặc biệt là những học thuyết của A.Xmít và Đ.Ricácđô, C.Mác và Ăngghen đã kế thừa những quan điểm hợp lý khoa học của những học thuyết này, đó là quan điểm duy vật trong trong nghiên cứu lĩnh vực khoa học kinh tế chính trị và học thuyết giá trị về lao động. Đồng thời phê phán và khắc phục tính chất chưa triệt để trong học thuyết giá trị về lao động và phương pháp siêu hình trong nghiên cứu. Trên cơ sở đó các ông đã xây dựng thành công học thuyết về giá trị thặng dư, luận chứng khoa học về bản chất , nguồn gốc kinh tế của chủ nghĩa tư bản, sự ra đời của chủ nghĩa xã hội.');
INSERT INTO `question_flash_muti` VALUES ('49', '6', null, '43', '61', '45', null, 'ý thứ 4', 'chủ nghĩa xã hội không tưởng, Anh, Pháp, H.Xanh Ximông, S.Phuriê, R.Ôoen, tư tưởng nhân đạo, chủ nghĩa xã hội.', null, null, null, null, 'Với chủ nghĩa xã hội không tưởng ở các nước Anh và Pháp, đặc biệt là nhà tư tưởng tiêu biểu H.Xanh Ximông, S.Phuriê và R.Ôoen. C.Mác và Ph.Ăngghen đã kế thừa những tư tưởng nhân đạo, sự phê phán hợp lý của các nhà tư tưởng này đối với những hạn chế của chủ nghĩa tư bản. Đồng thời, các ông cũng khắc phục và vượt qua hạn chế trong học thuyết của họ. Đó là tính chất không tưởng trong các học thuyết ấy. Từ đó xây dựng nên một lý luận mới – lý luận khoa học về chủ nghĩa xã hội.');
INSERT INTO `question_flash_muti` VALUES ('50', '6', null, '43', '61', '45', null, null, null, null, null, null, null, null);
INSERT INTO `question_flash_muti` VALUES ('51', null, null, '44', '63', '63', null, 'Ý thứ nhất', 'hệ thống các quan điểm, học thuyết khoa học, Mác xây dựng, Lenin phát triển', null, null, null, null, 'Là hệ thống các quan điểm và học thuyết khoa học do C.Mác và Ph.Ăngghen xây dựng, V.I.Leenin bảo vệ và phát triển, được hình thành và phát triển dựa trên cơ sở tổng kết thực tiễn và kế thừa những giá trị tư tưởng của nhân loại');
INSERT INTO `question_flash_muti` VALUES ('68', null, null, '44', '63', '63', null, 'Ý thứ hai là gì?', 'thế giới quan, phương pháp luận, chung nhất, nhận thức khoa học, thực tiễn cách mạng', null, null, null, null, 'là thế giới quan, phương pháp luận chung nhất của nhận thức khoa học và thực tiễn cách mạng');
INSERT INTO `question_flash_muti` VALUES ('69', null, null, '44', '63', '63', null, 'Ý thứ ba', 'khoa học, sự nghiệp giải phóng các giai cấp vô sản, nhân dân lao động, con người', null, null, null, null, 'là khoa học về sự nghiệp giải phóng giai cấp vô sản, giải phóng nhân dân lao động khỏi mọi chế độ áp bức, bóc lột, và tiến tới giải phóng con người.');
INSERT INTO `question_flash_muti` VALUES ('70', null, null, '44', '64', '64', null, 'Ý lớn thứ nhất', null, null, null, null, null, 'Điều kiện kinh tế - xã hội');
INSERT INTO `question_flash_muti` VALUES ('71', '6', null, '44', '64', '70', null, 'Ý nhỏ thứ nhất', 'năm 40- thế kỉ 19', null, null, null, null, 'Chủ nghĩa Mác-Lênin ra đời vào những năm 40 của thế kỉ XIX:');
INSERT INTO `question_flash_muti` VALUES ('72', '6', null, '44', '64', '70', null, 'ý nhỏ thứ 2', 'phương thức sản xuất tư bản, Tây Âu, phát triển, nền tảng, Cách mạng công nghiệp Anh, thế kỷ 18', null, null, null, null, 'Là thời kỳ phương thức sản xuất tư bản chủ nghĩa ở các nước Tây Âu đã phát triển mạnh mẽ trên nền tảng cuộc cách mạng công nghiệp được diễn ra trước tiên ở Anh vào cuối thế kỉ XVIII.');
INSERT INTO `question_flash_muti` VALUES ('73', '6', null, '44', '64', '70', null, 'ý nhỏ thứ ba', 'thủ công tư bản, tư bản chủ nghĩa, giai cấp vô sản', null, null, null, null, 'Cuộc cách mạng công nghiệp đánh dấu bước chuyển biến từ nền sản xuất thủ công tư bản sang nền đại công nghiệp tư bản chủ nghĩa, làm thay đổi sâu sắc cục diện xã hội, trước hết là sự hình thành và phát triển của giai cấp vô sản.');
INSERT INTO `question_flash_muti` VALUES ('74', '6', null, '44', '64', '70', null, 'ý nhỏ thứ 4', 'mâu thuẫn, lực lượng sản xuất, quan hệ sản xuất, 1825, Pháp, Anh, Đức', null, null, null, null, 'Thời kì này mâu thuẫn sâu sắc giữa Lực lượng sản xuất với Quan hệ sản xuất bộc lộ qua cuộc khủng hoảng kinh tế 1825 và hàng loạt các cuộc đấu tranh của giai cấp công nhân đã nổ ra ở Anh, Pháp, Đức.');
INSERT INTO `question_flash_muti` VALUES ('75', '6', null, '44', '64', '70', null, 'ý nhỏ thứ năm', 'giai cấp vô sản, độc lập, tiên phong', null, null, null, null, 'Giai cấp vô sản đã trở thành lực lượng chính trị độc lập, tiên phong trong cuộc đấu tranh cho nền dân chủ, công bằng, tiến bộ xã hội. Thực tiễn cách mạng đã đặt ra yêu cầu khách quan là phải có lí luận soi đường và CNMÁC ra đời đã đáp ứng được yêu cầu khách quan đó .');
INSERT INTO `question_flash_muti` VALUES ('76', null, null, '44', '64', '64', null, 'Ý lớn thứ 2', null, null, null, null, null, 'Tiền đề lý luận?');
INSERT INTO `question_flash_muti` VALUES ('77', '6', null, '44', '64', '76', null, 'Ý nhỏ thứ nhất', 'nhu cầu khách quan, kế thừa tinh hoa', null, null, null, null, 'Chủ nghĩa Mác ra đời không chỉ xuất phát từ nhu cầu khách quan lịch sử, mà còn là kết quả của sự kế thừa tinh hoa di sản lý luận của nhân loại, trong đó, trực tiếp nhất là triết học cổ điển Đức, kinh tế học chính trị cổ điển Anh và chủ nghĩa xã hội không tưởng Pháp và Anh:');
INSERT INTO `question_flash_muti` VALUES ('78', '6', null, '44', '64', '76', null, 'Ý nhỏ thứ 2', 'triết học cổ điển Đức, kế thừa, biện chứng - Ph.Hêghen, chủ nghĩa duy vật-L.Phoiơbắc', null, null, null, null, 'Với triết học cổ điển Đức, đặc biệt là triết học của Ph.Hêghen và L.Phoiơbắc đã ảnh hưởng sâu sắc đến sự hình thành thế giới quan và phương pháp luận triết học của chủ nghĩa Mác.\r\nCác nhà sáng lập của chủ nghĩa Mác đã kế thừa những nội dung cơ bản trong phép biện chứng của Ph.Hêghen, chủ nghĩa duy vật của L.Phoiơbắc. Khắc phục những những hạn chế cơ bản của hai học thuyết ấy, đó là triết học duy tâm (Hêghen) và phương pháp siêu hình (Phoiơbắc). Sáng lập ra chủ nghĩa duy vật biện chứng và phép biện chứng duy vật và được vận dụng vào nghiên cứu một cách khoa học những quy luật chung nhất của sự phát triển xã hội, nghiên cứu quy luật ra đời, phát triển suy tàn của chủ nghĩa tư bản và sự ra đời tất yếu của Chủ nghĩa xã hội.');
INSERT INTO `question_flash_muti` VALUES ('79', '6', null, '44', '64', '76', null, 'Ý nhỏ thứ ba', 'triết học cổ điển Anh, kế thừa, quan điểm hợp lý khoa học, A.Xmít, Đ.Ricácđô, giá trị thặng dư,', null, null, null, null, 'Với kinh tế học chính trị cổ điển Anh, đặc biệt là những học thuyết của A.Xmít và Đ.Ricácđô, C.Mác và Ăngghen đã kế thừa những quan điểm hợp lý khoa học của những học thuyết này, đó là quan điểm duy vật trong trong nghiên cứu lĩnh vực khoa học kinh tế chính trị và học thuyết giá trị về lao động. Đồng thời phê phán và khắc phục tính chất chưa triệt để trong học thuyết giá trị về lao động và phương pháp siêu hình trong nghiên cứu. Trên cơ sở đó các ông đã xây dựng thành công học thuyết về giá trị thặng dư, luận chứng khoa học về bản chất , nguồn gốc kinh tế của chủ nghĩa tư bản, sự ra đời của chủ nghĩa xã hội.');
INSERT INTO `question_flash_muti` VALUES ('80', '6', null, '44', '64', '76', null, 'ý thứ tư', 'chủ nghĩa xã hội không tưởng, Anh, Pháp, H.Xanh Ximông, S.Phuriê, R.Ôoen, tư tưởng nhân đạo, chủ nghĩa xã hội.', null, null, null, null, 'Với chủ nghĩa xã hội không tưởng ở các nước Anh và Pháp, đặc biệt là nhà tư tưởng tiêu biểu H.Xanh Ximông, S.Phuriê và R.Ôoen. C.Mác và Ph.Ăngghen đã kế thừa những tư tưởng nhân đạo, sự phê phán hợp lý của các nhà tư tưởng này đối với những hạn chế của chủ nghĩa tư bản. Đồng thời, các ông cũng khắc phục và vượt qua hạn chế trong học thuyết của họ. Đó là tính chất không tưởng trong các học thuyết ấy. Từ đó xây dựng nên một lý luận mới – lý luận khoa học về chủ nghĩa xã hội.');
INSERT INTO `question_flash_muti` VALUES ('81', null, null, '44', '64', '64', null, 'Ý lớn thứ ba', 'Tiền đề khoa học tự nhiên; bảo toàn năng lượng, tính thống nhất, ; tính tất yếu khách quan,', null, null, null, null, 'Khẳng định tính chất bảo toàn năng lượng trong quá trình biến đổi của vật chất trong giới tự nhiên; tính thống nhất về cơ sở vật chất của mọi sự sống là tế bào; tính tất yếu khách quan của quá trình phát triển các loài sinh vật trên trái đất .Những quan điểm này đóng vai trò là bằng chứng xác thực ( ở tầm khoa học ) của các quan điểm biện chứng về giới tự nhiên.');
INSERT INTO `question_flash_muti` VALUES ('84', null, null, '44', '65', '65', null, 'ý thứ nhất', 'hệ thống tri thức phong phú, kinh tế học chính trị, chi phối quá trình sản xuất, Chủ nghĩa xã hội khoa học, cách mạng xã hội chủ nghĩa, sứ mệnh lịch sử', null, null, null, null, 'Nội dung của chủ nghĩa Mác-Lênin bao gồm hệ thống tri thức phong phú bao quát nhiều lĩnh vực như giá trị lịch sử, thời đại và khoa học to lớn; nhưng triết học, kinh tế học chính trị, chủ nghĩa xã hội khoa học là những bộ phận lý luận quan trọng nhất. Triết học là hệ thống tri thức chung nhất về thế giới, về vị trí, vai trò của con ngườitrong thế giới ấy. Kinh tế học chính trị là hệ thống tri thức về những quy luật chi phối quá trình sản xuất và trao đổi tư liệu sinh hoạt vật chất trong đời sống xã hội mà trọng tâm của nó là những quy luật kinh tế của quá trình vận động, phát triển, diệt vong tất yếu của hình thái kinh tế - xã hội tư bản chủ nghĩa cũng như sự ra đời tất yếu của hình thái kinh tế - xã hội cộng sản chủ nghĩa. Chủ nghĩa xã hội khoa học là hệ thống tri thức chung nhất về cách mạng xã hội chủ nghĩa và quá trình hình thành, phát triển của hình thái kinh tế - xã hội cộng sản chủ nghĩa; về sứ mệnh lịch sử của giai cấp công nhân trong sự nghiệp xây dựng hình thái kinh tế đó.');
INSERT INTO `question_flash_muti` VALUES ('85', null, null, '44', '65', '65', null, 'ý thứ hai', 'sự khác nhau tương đối, hình thái kinh tế- xã hội cộng sản \r\nchủ nghĩa, chủ nghĩa xã hội, chủ nghĩa cộng sản.', null, null, null, null, 'Giữa các bộ phận lý luận chủ nghĩa Mác- Lênin có sự khác nhau tương đối, thể hiện ở chỗ chủ nghĩa xã hội khoa học không nghiên cứu những quy luật xã hội tác động trong tất cả hoặc trong nhiều hình thái kinh tế - xã hội như chủ nghĩa duy vật lịch sử, mà chỉ nghiên cứu các quy luật đặc thù của sự hình thành, phát triển của hình thái kinh tế- xã hội cộng sản chủ nghĩa. Chủ nghĩa xã hội khoa học cũng không nghiên cứu các quan hệ kinh tế như kinh tế chính trị, mà chỉ nghiên cứu các quan hệ chính trị - xã hội của chủ nghĩa xã hội và chủ nghĩa cộng sản.');
INSERT INTO `question_flash_muti` VALUES ('86', null, null, '44', '65', '65', null, 'ý thứ ba', 'sự thống nhất tương đối, quan điểm duy vật, thế giới quan duy vật biện chứng và phép biện chứng duy vật giá trị thặng dư', null, null, null, null, 'Giữa các bộ phận lý luận chủ nghĩa Mác-Lênin có sự thống nhất tương đối, thể hiện ở quan điểm duy vật về lịch sử mà tư tưởng chính của nó là do sự phát triển khách quan của lực lượng sản xuất nên từ một hình thái kinh tế - xã hội này nảy sinh ra một hình thái kinh tế - xã hội khác tiến bộ hơn và chính quan niệm như thế đã thay thế sự lộn xộn, tùy tiện trong các quan niệm về xã hội trong các học thuyết trước đó; thể hiện ở việc C.Mác và Ph.Ăngghen vận dụng thế giới quan duy vật biện chứng và phép biện chứng duy vật vào việc nghiên cứu kinh tế, từ đó sáng tạo ra học thuyết giá trị thặng dư để nhận thức chính xác sự xuất hiện, phát triển và diệt vong tất yếu của chủ nghĩa tư bản. Đến lượt mình, học thuyết về giá trị thặng dư cùng với quan điểm duy vật về lịch sử đã đưa sự phát triển của chủ nghĩa xã hội từ không tưởng đến khoa học.');
INSERT INTO `question_flash_muti` VALUES ('87', '6', null, '44', '66', '66', null, 'Ý lớn thứ nhất là gì?', 'hệ thống tri thứ lý luận, con người, về thế giới, bản thân, vị trí của con người', null, null, null, '1545061634', 'Khái quát chung: Triết học là hệ thống tri thức lý luận chung nhất của con người về thế giới, về bản thân con người và vị trí của con người trong thế giới đó.');
INSERT INTO `question_flash_muti` VALUES ('88', '6', null, '44', '66', '66', null, 'Ý lớn thứ hai', 'giải quyết mối quan hệ, vật chất, ý thức', null, null, null, '1545061634', 'Vấn đề cơ bản của triết học từ xưa đến nay đều xoay quanh giải quyết mối quan hệ giữa vật chất và ý thức .Đây là vấn đề xuyên suốt lịch sử triết học.Vấn đề cơ bản của triết học có hai mặt, mỗi mặt phải trả lời một câu hỏi lớn .');
INSERT INTO `question_flash_muti` VALUES ('89', '6', null, '44', '66', '88', null, 'Ý thứ nhất?', 'vật chất, ý thức, có trước, có sau, quyết định', null, null, null, '1545061634', 'Vật chất và ý thức cái nào có trước, cái nào có sau? Cái nào quyết định cái nào?');
INSERT INTO `question_flash_muti` VALUES ('90', '6', null, '44', '66', '88', null, 'Ý thứ hai?', 'con người, khả năng nhận thức, thế giới,', null, null, null, '1545061634', 'Con người có khả năng nhận thức được thế giới hay không?');
INSERT INTO `question_flash_muti` VALUES ('91', '6', null, '44', '67', '67', null, 'Ý lớn thứ nhất', 'bản chất, vật chất có trước, quyết định ý thức', null, null, null, '1545061951', 'Chủ nghĩa duy vật: cho rằng bản chất thế giới là vật chất,vật chất có trước, ý thức có sau và vật chất quyết định ý thức.');
INSERT INTO `question_flash_muti` VALUES ('92', null, null, '44', '67', '67', null, 'ý lớn thứ hai?', 'bản chất thế giới, ý thức, ý thức-trước, vật chất-sau, ý thức, quyết định, vật chất', null, null, null, null, 'Chủ nghĩa duy tâm: cho rằng bản chất thế giới là ý thức, ý thức có trước, vật chất có sau và ý thức quyết định vật chất.');
INSERT INTO `question_flash_muti` VALUES ('93', '6', null, '44', '67', '92', null, 'ý nhỏ thứ nhất?', 'nguồn gốc nhận thức, nguồn gốc xã hội, phiến diện, đặc tính, quá trình nhận thức', null, null, null, null, 'Chủ nghĩa duy tâm có nguồn gốc nhận thức và nguồn gốc xã hội, đó là: sự xem xét phiến diện, tuyệt đối hóa, thần thành hóa một mặt, một đặc tính nào đó của quá trình nhận thức và thường gắn với lợi ích của các giai cấp, tầng lớp áp bức, bóc lột nhân dân lao động. Chủ nghĩa duy tâm và tôn giáo cũng thường có mối liên hệ mật thiết với nhau, nương tựa vào nhau để cùng tồn tại và phát triển.');
INSERT INTO `question_flash_muti` VALUES ('94', '6', null, '44', '67', '92', null, 'ý nhỏ thứ hai?', 'chủ nghĩa duy tâm chủ quan, thừa nhận ý thức, phủ nhận tồn tại khách quan, phức hợp những cảm giác', null, null, null, null, 'Chủ nghĩa duy tâm chủ quan: Thừa nhận tính thứ nhất của ý thức con người, phủ nhận sự tồn tại khách quan của hiện thực, khẳng định mọi sự vật, hiện tượng chỉ là “ phức hợp những cảm giác “ của cá nhân.');
INSERT INTO `question_flash_muti` VALUES ('95', '6', null, '44', '67', '92', null, 'ý nhỏ thứ 3', 'chủ nghĩa duy tâm khách quan, thừa nhận tinh thần, ý thức khách quan,', null, null, null, null, 'Chủ nghĩa duy tâm khách quan: Thừa nhận tính thứ nhất của tinh thần, ý thức nhưng đó là đó là tinh thần, ý thức khách quan có trước, tồn tại độc lập với giới tự nhiên, con người');
INSERT INTO `question_flash_muti` VALUES ('99', '6', null, '44', '70', '70', null, 'ý thứ nhất là gì?', 'Chủ nghĩa duy vật chất phác, học thuyết triết học duy vật, thời cổ ở Ấn Độ, Trung Quốc, Hy Lạp.', null, null, null, '1545125098', 'Chủ nghĩa duy vật chất phác với hình thức điển hình của nó là các học thuyết triết học duy vật thời cổ ở Ấn Độ, Trung Quốc và Hy Lạp.');
INSERT INTO `question_flash_muti` VALUES ('100', '6', null, '44', '70', '70', null, 'ý thứ hai là gì?', 'Chủ nghĩa duy vật siêu hình học thuyết triết học duy vật thời cận đại, Tây Âu, Anh Pháp', null, null, null, '1545125098', 'Chủ nghĩa duy vật siêu hình với hình thức điển hình của nó là các học thuyết triết học duy vật thời cận đại ( thế kỷ XVII-XVIII ) ở các nước Tây Âu (tiêu biểu là chủ nghĩa duy vật cận đại nước Anh và Pháp )');
INSERT INTO `question_flash_muti` VALUES ('101', '6', null, '44', '70', '70', null, 'ý thứ ba', 'Chủ nghĩa duy duy vật biện chứng, C.Mác và Ph.Ăngghe, thế kỉ 19	Chủ nghĩa duy duy vật biện chứng do C.Mác và Ph.Ăngghen sáng lập từ giữa thế kỉ XIX.', null, null, null, '1545125098', 'Chủ nghĩa duy duy vật biện chứng do C.Mác và Ph.Ăngghen sáng lập từ giữa thế kỉ XIX.');
INSERT INTO `question_flash_muti` VALUES ('102', '6', null, '44', '71', '71', null, 'ý thứ nhất là gì?', 'lý giải các tồn tại, giải thích các hiện tượng', null, null, null, '1545125503', 'nó không chỉ đứng trên lập trường duy vật trong việc lý giải các tồn tại trong giới tự nhiên ( như chủ nghĩa duy vật siêu hình trước đây ) mà còn đứng trên lập trường duy vật trong việc giải thích các hiện tượng, quá trình diễn ra trong đời sống xã hội loài người – đó chính là những quan điểm duy vật về lịch sử hay chủ nghĩa duy vật lịch sử');
INSERT INTO `question_flash_muti` VALUES ('103', null, null, '44', '71', '71', null, 'ý thứ hai là gì?', 'định hướng nhận thức, cải tạo thế giới', null, null, null, null, 'nó không chỉ đứng trên lập trường duy vật trong quá trình định hướng nhận thức và cải tạo thế giới mà nó còn sử dụng phương pháp biện chứng trong quá trình ấy. Từ đó tạo nên sự đúng đắn, khoa học trong việc lý giải thế giới và cải tạo thế giới.');
INSERT INTO `question_flash_muti` VALUES ('104', null, null, '44', '71', '71', null, 'ý thứ ba', 'kế thừa những tinh hoa của lịch sử triết học, tổng kết những thành tựu lớn của khoa học', null, null, null, null, 'nội dung của chủ nghĩa duy vật biện chứng được xây dựng trên cơ sở kế thừa những tinh hoa của lịch sử triết học và trên cơ sở tổng kết những thành tựu lớn của khoa học, của thực tiễn trong thời đại mới; nó trở thành thế giới quan và phương pháp luận khoa học của giai cấp cách mạng và của các lực lượng tiến bộ trong thời đại ngày nay');
INSERT INTO `question_flash_muti` VALUES ('105', '6', null, '46', '77', '77', null, 'Ý 1 là gì?', 'quan điểm, quan niệm, lý luận', null, null, null, '1545212540', 'Bao gồm hệ thống các quan điểm, quan niệm, lý luận được thể hiện trong toàn bộ di sản của Người. Di sản của Người gồm cuộc đời, sự nghiệp, các bài nói, bài viết,...');
INSERT INTO `question_flash_muti` VALUES ('106', '6', null, '46', '77', '77', null, 'Ý 2 là gì?', 'vận động, hiện thực hóa các quan điểm, lý luận đó', null, null, null, '1545212540', 'Còn là quá trình vận động, hiện thực hóa các quan điểm, lý luận đó trong thực tiễn CMVN. Đó là quá trình mang tính quy luật bao gồm 2 mặt thống nhất biện chứng: sản sinh tư tưởng và hiện thực hóa tư tưởng theo mục tiêu độc lập dân tộc, dân chủ, chủ nghĩa xã hội, giải phóng dân tộc, gp giai cấp, gp con người.');
INSERT INTO `question_flash_muti` VALUES ('107', '6', null, '46', '78', '78', null, 'Ý 1 là gì?', null, null, null, null, '1545212824', null);
INSERT INTO `question_flash_muti` VALUES ('108', '6', null, '46', '79', '79', null, 'Ý 1 là gì?', 'bám sát thực tiễn CM', null, null, null, '1545214495', 'HCM luôn bám sát thực tiễn CM dân tộc và thế giới, coi trọng tổng kết thực tiễn như là một biện pháp không chỉ nâng cao năng lực hoạt động thực tiễn mà còn là điều kiện nâng cao trình độ lý luận');
INSERT INTO `question_flash_muti` VALUES ('109', '6', null, '46', '79', '79', null, 'Ý 2 là gì?', 'kết hợp lý luận với thực tiễn, lời nói đi đôi với việc làm', null, null, null, '1545214495', 'HCM coi trọng việc kết hợp lý luận với thực tiễn, lời nói đi đôi với việc làm. Người khẳng định thực tiễn không có lý luận hướng dẫn thì thành thực tiễn mù quáng, dễ mắc bệnh chủ quan, lý luận mà không liên hệ với thực tiễn là lý luận suông');
INSERT INTO `question_flash_muti` VALUES ('110', '6', null, '46', '79', '79', null, 'ý 3 là gì?', 'vận dụng và phát triển sáng tạo CN Mác- Lenin', null, null, null, '1545214495', 'HCM luôn xuất phát từ thực tiễn CM VN, vận dụng và phát triển sáng tạo CN Mác- Lenin vào thực tiễn đất nước, đề ra đường lối CM đúng đắn, lãnh đạo đất nước ta vượt qua vượt qua khó khăn, thử thách, giành thắng lợi vẻ vang');
INSERT INTO `question_flash_muti` VALUES ('111', '6', null, '46', '80', '80', null, 'Ý 1 là gì?', 'xây dựng lý luận, trực tiếp tổ chức, lãnh đạo', null, null, null, '1545214617', 'HCM là một nhà lý luận- thực tiễn, Người xây dựng lý luận, vạch ra cương lĩnh, đường lối, chủ trương CM và trực tiếp tổ chức, lãnh đạo thực hiện');
INSERT INTO `question_flash_muti` VALUES ('112', '6', null, '46', '80', '80', null, 'Ý 2 là gì?', 'tác phẩm, bài nói, bài viết , hoạt động thực tiễn', null, null, null, '1545214617', 'Nghiên cứu TTHCM không chỉ căn cứ vào các tác phẩm, bài nói, bài viết mà cần coi trọng hoạt động thực tiễn của Người, thực tiễn CM dưới sự tổ chức và lãnh đạo của Đảng do HCM đứng đầu');
INSERT INTO `question_flash_muti` VALUES ('113', '6', null, '46', '80', '80', null, 'ý 3 là gì?', 'Kết quả hành động thực tiễn', null, null, null, '1545214617', 'Kết quả hành động thực tiễn, chủ nghĩa anh hùng CM trong chiến đấu và xây dựng của nhân dân VN chính là lời giải thích rõ ràng giá trị khoa học của TTHCM');
INSERT INTO `question_flash_muti` VALUES ('114', '6', null, '46', '81', '81', null, 'Ý 1 là gì?', 'phương pháp luận chung,lịch sử và phương pháp logic', null, null, null, '1545214719', 'Giữa phương pháp nghiên cứu và nội dung nghiên cứu có mối liên hệ mật thiết với nhau, ngoài các nguyên tắc phương pháp luận chung cần phải vận dụng một phương pháp nghiên cứu cụ thể, phù hợp. Vận dụng phương pháp lịch sử và phương pháp logic trong nghiên cứu TTHCM');
INSERT INTO `question_flash_muti` VALUES ('115', '6', null, '46', '81', '81', null, 'Ý 2 là gì?', 'phương pháp nghiên cứu liên ngành', null, null, null, '1545214719', 'Vận dụng phương pháp liên ngành trong TTHCM. Là một nhà tư tưởng, nhà khoa học, HCM đã thể hiện tư tưởng của mình như một hệ thống, bao quát nhiều lĩnh vực, trong mỗi lĩnh vực lại có thể tìm thấy những hệ thống nhỏ. Trước một đối tượng nghiên cứu đa dạng và phong phú như vậy thì phải áp dụng phương pháp nghiên cứu liên ngành');
INSERT INTO `question_flash_muti` VALUES ('116', '6', null, '46', '81', '81', null, 'ý 3 là gì?', 'phân tích, tổng hợp, so sánh, đối chiếu, thống kê trắc nghiệm...', null, null, null, '1545214719', 'Cần phải đổi mới và hiện đại hóa các phương pháp nghiên cứu cụ thể trên cơ sở không ngừng phát triển và hoàn thiện lý luận và phương pháp luận khoa học nói chung. Các phương pháp cụ thể thường được áp dụng: phân tích, tổng hợp, so sánh, đối chiếu, thống kê trắc nghiệm...');
INSERT INTO `question_flash_muti` VALUES ('117', '6', null, '46', '82', '82', null, 'Ý 1 là gì?', 'Theo Lenin:không được quên mối liên hệ lịch sử căn bản', null, null, null, '1545215181', 'Trong nghiên cứu khoa học, theo Lenin không được quên mối liên hệ lịch sử căn bản khi xem xét một sự vật hiện tượng nhất định đã xuất hiện trong lịch sử như thế nào, hiện tượng đó đã trải qua những giai đoạn phát triển chủ yếu nào và đứng trên quan điểm của sự phát triển đó để xem xét hiện nay nó đã trở thành như thế nào?');
INSERT INTO `question_flash_muti` VALUES ('118', '6', null, '46', '82', '82', null, 'Ý 2 là gì?', 'nắm vững quan điểm lịch sử- cụ thể', null, null, null, '1545215181', 'Khi học tập, nghiên cứu TTHCM cần nắm vững quan điểm lịch sử- cụ thể mới giúp chúng ta nhận thức được bản chất TTHCM');
INSERT INTO `question_flash_muti` VALUES ('119', '6', null, '44', '83', '83', null, 'Ý 1 là gì?', 'Ở thời kỳ cổ đại, vật chất, cụ thể, trực quan', null, null, null, '1545218360', 'Thời kỳ cổ đại. Các nhà triết học duy vật cổ đại thường coi vật chất là một vật thể nào đó, cụ thể, mang lại tính trực quan cảm tính, có thể là vật hữu hình. Xu hướng chung của các nhà triết học thời kỳ này là như vậy và cho rằng các vật thể đó là những đơn vị cuối cùng, tạo ra tất cả các sự vật, hiện tượng trong thế giới.');
INSERT INTO `question_flash_muti` VALUES ('120', '6', null, '44', '83', '83', null, 'Ý 2 là gì?', null, null, null, null, '1545218360', 'Ở thời kỳ cận đại');
INSERT INTO `question_flash_muti` VALUES ('121', '6', null, '44', '83', '120', null, 'ý thứ 2.1 là gì?', 'đồng nhất, vật chất với nguyên từ, chân lý hoàn chỉnh, bất di bất dịch', null, null, null, '1545218360', 'Vào thế kỷ XVII, XVIII phát huy truyền thống của các nhà duy vật thời cổ đại, các nhà triết học trong giai đoạn này cũng đồng nhất vật chất với nguyên tử ( vật chất trùng với nguyên tử ). Nhưng do khoa học tự nhiên phát triển mạnh đặc biệt là môn cơ học, với xu thế chung của các nhà triết học thời kỳ này như: Galilê, Đêcáctơ, Niutơn…. Coi vật chất đồng nhất với khối lượng và khối lượng là bất biến. Đồng thời do ảnh hưởng của phương pháp tư duy siêu hình, những quan niệm trên đã được coi như những chân lý hoàn chỉnh, bất di bất dịch. Việc quan niệm khối lượng của các vật thể là bất biến, không phụ thuộc vào vận động là một trong những sai lầm ở thời kỳ này. Niutơn đã đòng nhất khối lượng với vật chất, coi vận động của vật chất chỉ là vận động cơ học, tách rời vận động không gian, thời gian với vật chất. Đó là những quan điểm của các nhà triết học thời kỳ này.');
INSERT INTO `question_flash_muti` VALUES ('122', '6', null, '44', '83', '120', null, 'Ý thứ 2.2 là gì?', '1 số phát minh, căn bản quan niệm cổ truyền về vật chất, chứng minh rằng sự đồng nhất với những dạng cụ thể của vật chất', null, null, null, '1545218360', 'Đến cuối thế kỉ XIX, đầu thế kỷ XX, một số phát minh quan trọng trong khoa học tự nhiên đặc biệt là trong lĩnh vực vật lý học đã đem lại những hiểu biết mới về cấu trúc của vật chất, nó đã làm thay đổi căn bản quan niệm cổ truyền về vật chất. Cụ thể như sự phát hiện ra tia X của Rơnghen, phóng xạ của Bécơnen đã chứng tỏ rằng nguyên từ không phải là không thể phân chia được và không thể chuyển hóa sang các nguyên từ khác, bác bỏ quan niệm siêu hình cho rằng nguyên tố hóa học bất biến. Năm 1981, Tômxơn nhà vật lý người Anh đã phát hiện ra điện tử. Điện tử là một trong những yếu tố tạo nên nguyên tử. Phát minh này chứng tỏ rằng nguyên tử không phải là đơn vị cuối cùng tạo nên thế giới vật chất. Hay sự phát hiện quan trọng là trong quá trình vận động, khối lượng của điện tử tăng khi vận tốc của nó tăng. Như vậy, khối lượng cũng không phải là cái bất biến. Phát mình này đã phủ nhận hoàn toàn quan điểm siêu hình coi khối lượng là bất biến.Những phát minh trong vật lý đã chứng minh rằng sự đồng nhất với những dạng cụ thể của vật chất, với những thuộc tính của vật chất như chủ nghĩa duy vật trước Mác quan niệm là căn cứ để chủ nghĩa duy tâm lợi dụng chống lại chủ nghĩa duy vật, bảo vệ những luận điểm duy tâm. Các nhà triết học của chủ nghĩa duy tâm đã cho rằng “ vật chất tiêu tan mất” làm cho toàn bộ nền tảng của chủ nghĩa duy vật bị sụp đổ hoàn toàn.');
